#include "Q.h"
BEGIN
L 0:						// Inicio del programa
STAT(0)	// Memoria estática
CODE(0)
	R7 = R7 - 4;
	R6 = R7;
	R7 = R7 - 4;		//Generated by line 2
	R0=13;			// StoreOperand at line:2
//initializeVar
	I(R6 - 4) = R0;		//Generated by line 3
	I(R7) = R0;	//Generated by print at line: 3
	I(R7 - 4) = R1;	//Generated by print at line: 3
	I(R7 - 8) = R2;	//Generated by print at line: 3
	R7 = R7 - 12;	//Generated by print at line: 3
	R0 = 1;	//Generated by print at line: 3
	R2 = I(R6 - 4);	//Generated by print
STAT(1)	//Generated by print
	STR(0x11ffc, "%i\n");	//Generated by print
CODE(1)	//Generated by print
	R1 = 0x11ffc;	//Generated by print
	R0 = 1;	//Generated by print
	GT(-12);	//Generated by print
L 1:
	R0 = I(R7);	//Generated by print at line: 3
	R1 = I(R7 - 4);	//Generated by print at line: 3
	R2 = I(R7 - 8);	//Generated by print at line: 3
	R7 = R7 - 8;		//Generated by line 4
	R0=8;			// StoreOperand at line:4
//initializeVar
	I(R6 - 8) = R0;		//Generated by line 5
	I(R7) = R0;	//Generated by print at line: 5
	I(R7 - 4) = R1;	//Generated by print at line: 5
	I(R7 - 8) = R2;	//Generated by print at line: 5
	R7 = R7 - 12;	//Generated by print at line: 5
	R0 = 2;	//Generated by print at line: 5
	R2 = I(R6 - 8);	//Generated by print
STAT(2)	//Generated by print
	STR(0x11ff4, "%i\n");	//Generated by print
CODE(2)	//Generated by print
	R1 = 0x11ff4;	//Generated by print
	R0 = 2;	//Generated by print
	GT(-12);	//Generated by print
L 2:
	R0 = I(R7);	//Generated by print at line: 5
	R1 = I(R7 - 4);	//Generated by print at line: 5
	R2 = I(R7 - 8);	//Generated by print at line: 5
	R7 = R7 - 12;		//Generated by line 6
	R0=25;			// StoreOperand at line:6
//initializeVar
	I(R6 - 12) = R0;		//Generated by line 7
	I(R7) = R0;	//Generated by print at line: 7
	I(R7 - 4) = R1;	//Generated by print at line: 7
	I(R7 - 8) = R2;	//Generated by print at line: 7
	R7 = R7 - 12;	//Generated by print at line: 7
	R0 = 3;	//Generated by print at line: 7
	R2 = I(R6 - 12);	//Generated by print
STAT(3)	//Generated by print
	STR(0x11fec, "%i\n");	//Generated by print
CODE(3)	//Generated by print
	R1 = 0x11fec;	//Generated by print
	R0 = 3;	//Generated by print
	GT(-12);	//Generated by print
L 3:
	R0 = I(R7);	//Generated by print at line: 7
	R1 = I(R7 - 4);	//Generated by print at line: 7
	R2 = I(R7 - 8);	//Generated by print at line: 7
GT(-2);
END
