#include "Q.h"
BEGIN
L 0:						// Inicio del programa
STAT(0)	// Memoria estática
CODE(0)
	R7 = R7 - 4;
	R6 = R7;
STAT(1)		//Generated by line 1
	DAT(0x11ffc,I,0);		//Generated by line 1
//id: a
CODE(1)		//Generated by declareVar at line 1
	R0 = 13;			// StoreOperand at line:3
// pack->varType = 1, initializeVar3
	I(0x11ffc) = R0;		//Generated by line 3
//inside method (no params)
	GT(2);		// Generated by meth (no params) at 3
L 1:	// Generated by meth (no params) at 3
//printing an ID: a
	I(R7 - 4) = R0;	//Generated by print at line: 4
	I(R7 - 8) = R1;	//Generated by print at line: 4
	I(R7 - 12) = R2;	//Generated by print at line: 4
	R7 = R7 - 16;	//Generated by print at line: 4
	R0 = 3;	//Generated by print at line: 4
	R2 = I(0x11ffc);	//Generated by print
STAT(2)	//Generated by print
	STR(0x11ff4, "%i\n");	//Generated by print
CODE(2)	//Generated by print
	R1 = 0x11ff4;	//Generated by print
	R0 = 3;	//Generated by print
	GT(-12);	//Generated by print
L 3:	//Generated by print
	R0 = I(R7 + 12);	//Generated by print at line: 4
	R1 = I(R7 + 8);	//Generated by print at line: 4
	R2 = I(R7 + 4);	//Generated by print at line: 4
	R7 = R7 + 16;	//Generated by print at line: 4
	I(0x11fec) = 4;	// Generated by meth (no params) at 5
	GT(4);	// Generated by methReturn (no params) at 5
L 2:	// Generated by meth name at 5
//function call (no params)
	R0 = I(0x11fec);		// Generated by meth (no params) at 7
L R0:	// Generated by meth (no params) at 7
GT(-2);
END
