#include "Q.h"
BEGIN
L 0:						// Inicio del programa
STAT(0)	// Memoria estática
CODE(0)
	R7 = R7 - 4;
	R6 = R7;
	R7 = R7 - 4;		//Generated by line 2
	R0=8;			// StoreOperand at line:2
//initializeVar
	I(R6 - 4) = R0;		//Generated by line 3
	I(R7) = R0;	//Generated by print at line: 3
	I(R7 - 4) = R1;	//Generated by print at line: 3
	I(R7 - 8) = R2;	//Generated by print at line: 3
	R7 = R7 - 12;	//Generated by print at line: 3
	R0 = 1;	//Generated by print at line: 3
	R2 = I(R6 - 4);	//Generated by print
STAT(1)	//Generated by print
	STR(0x11ffc, "%i\n");	//Generated by print
CODE(1)	//Generated by print
	R1 = 0x11ffc;	//Generated by print
	R0 = 1;	//Generated by print
	GT(-12);	//Generated by print
L 1:
	R0 = I(R7);	//Generated by print at line: 3
	R1 = I(R7 - 4);	//Generated by print at line: 3
	R2 = I(R7 - 8);	//Generated by print at line: 3
GT(-2);
END
